{
    "question": "What is the output of the following code?\n\n```python\nimport math\n\ntry:\n    print(math.pow(2))\nexcept TypeError:\n    print('A')\nexcept:\n    print('B')\n```",
    "choices": [
        {
            "choice": "`A`",
            "correct": "false"
        },
        {
            "choice": "The program will cause the `ValueError` exception",
            "correct": "false"
        },
        {
            "choice": "`B`",
            "correct": "true"
        }
    ]
}